packages:
  - playground
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unix-dgram: true
  workerd: true

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@types/node': ^26.1.1
  '@vitejs/plugin-vue': ^6.0.7
  bumpp: ^11.1.0
  eslint: ^10.7.0
  typescript: ~6.0.3
  unplugin-dts: ^1.0.3
  vite: ^8.1.4
  vue: ^3.5.39
  vue-tsc: ^3.3.7
  wrangler: ^4.113.0
