packages:
  - playground
  - packages/*

catalog:
  '@antfu/eslint-config': ^2.6.3
  '@types/node': ^24.12.0
  '@vitejs/plugin-vue': ^6.0.5
  bumpp: ^11.1.0
  eslint: ^9.39.4
  netlify-cli: ^24.3.0
  typescript: ~5.9.3
  vite: ^8.0.0
  vue: ^3.5.30
  vue-tsc: ^3.2.6
